language: java
notifications:
  slack: hcmiuiotclub:XXa9fURMSw6YOhM2Lptat411

cache:
  directories:
  - .autoconf
  - $HOME/.m2

matrix:
  include:
  # Ubuntu Linux (trusty) / Oracle JDK 8 / Headed (AWT Robot)
  - os: linux
    dist: trusty
    jdk: oraclejdk11
    env:
    - _JAVA_OPTIONS="-Dtestfx.robot=awt"
  # Ubuntu Linux (trusty) / Oracle JDK 8 / Headed (Glass Robot) / HiDPI
#  - os: linux
#    dist: trusty
#    jdk: oraclejdk11
#    env:
#    - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
  # Ubuntu Linux (trusty) / Oracle JDK 8 / Headless
#  - os: linux
#    dist: trusty
#    jdk: oraclejdk11
#    env:
#    - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
  # macOS / Oracle JDK 8 / Headless
#  - os: osx
#    osx_image: xcode9.4
#    jdk: oraclejdk11
#    env:
#    - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
  # Headed macOS is not currently possible on Travis.
#
#addons:
#  apt:
#    packages:
#    - oracle-java11-installer

before_install:
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true
