language: java
notifications:
  email:
    recipients:
      - hungthuanmk@gmail.com
      - tranduckhoatcu@gmail.com
      - lt1679848@gmail.com
      - trungnguyen10051998@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
